
name: GH Actions Cron Schedule
on:
  workflow_dispatch:
  schedule:
    # Every M-F at 12:00am run this job
    - cron:  "0 0 * * 1-5"
    
jobs:
  check-image-version:
    uses: securesign/actions/.github/workflows/check-image-version.yaml@main
    strategy:
      matrix:
        branch: [main]
    with:
      branch: ${{ matrix.branch }}
      images: '["registry.access.redhat.com/ubi9/go-toolset", "registry.access.redhat.com/ubi9/ubi-minimal", "registry.redhat.io/rhel8/mariadb-105", "registry.redhat.io/rhel8/redis-6"]'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      registry_redhat_io_username: ${{ secrets.REGISTRY_REDHAT_IO_USERNAME }}
      registry_redhat_io_password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}